In [19]:
import torch
import torch.nn as nn
import helper_utils
import torch.optim as optim
import pandas as pd

torch.manual_seed(42)

df = pd.read_csv(r'C:\Users\SriniAchuthan\Downloads\data_with_features.csv')
print(df)


    distance_miles  time_of_day_hours  is_weekend  delivery_time_minutes
0             1.60               8.20           0                   7.22
1            13.09              16.80           1                  32.41
2             6.97               8.02           1                  17.47
3            10.66              16.07           0                  37.17
4            18.24              13.47           0                  38.36
..             ...                ...         ...                    ...
95            7.63              16.53           0                  30.05
96           14.79               8.00           0                  54.38
97           18.05               8.00           0                  64.14
98           17.85              19.36           0                  39.74
99           15.82              19.52           0                  31.65

[100 rows x 4 columns]


In [13]:
a = torch.tensor(3)
b = torch.tensor(4)
print(a+b)

tensor(7)


In [8]:
import math
distances = torch.tensor([[10.0] , [20.0] , [30.0] , [40.0] , [50.0]] , dtype = torch.float32)
time = torch.tensor([[1.0] , [2.0] , [3.0] , [4.0] , [5.0] ] , dtype = torch.float32)
print('Speed:',distances/time)

Speed: tensor([[10.],
        [10.],
        [10.],
        [10.],
        [10.]])


In [14]:

  # Step 1: Define the class
class DeliveryModel(nn.Module):
      def __init__(self):
          super().__init__()
          self.fc1 = nn.Linear(10, 64)
          self.fc2 = nn.Linear(64, 1)

      def forward(self, x):
          x = torch.relu(self.fc1(x))
          return self.fc2(x)

  # Step 2: Instantiate
model = DeliveryModel()

  # Step 3: Optimizer (also fix the syntax error here)
optimizer = optim.Adam(model.parameters(), lr=0.01)  # lr= not loss=

  # Step 4: Loss function
loss_function = nn.MSELoss()

In [19]:
# model = nn.Sequential(nn.Linear(1,1))

# for epoch in range(500):
#     # Reset the optimizer's gradients
#     optimizer.zero_grad()
#     # Make predictions (forward pass)
#     outputs = model(distances)
#     # Calculate the loss
#     loss = loss_function(outputs, time)
#     # Calculate adjustments (backward pass)
#     loss.backward()
#     # Update the model's parameters
#     optimizer.step()
#     # Print loss every 50 epochs
#     if (epoch + 1) % 50 == 0:
#         print(f"Epoch {epoch + 1}: Loss = {loss.item()}")
    

Epoch 50: Loss = 937.9573974609375
Epoch 100: Loss = 937.9573974609375
Epoch 150: Loss = 937.9573974609375
Epoch 200: Loss = 937.9573974609375
Epoch 250: Loss = 937.9573974609375
Epoch 300: Loss = 937.9573974609375
Epoch 350: Loss = 937.9573974609375
Epoch 400: Loss = 937.9573974609375
Epoch 450: Loss = 937.9573974609375
Epoch 500: Loss = 937.9573974609375


In [26]:
model = nn.Sequential(nn.Linear(1,1))

marks1 = torch.tensor([[23.0],[24.0],[25.0],[26.0]] , dtype = torch.float32)
marks2 = torch.tensor([[1.0] , [2.0] , [3.0] , [4.0]] , dtype = torch.float32)

marks1 = (marks1 - marks1.mean()) / marks1.std()
marks2 = (marks2 - marks2.mean()) / marks2.std()

for epoch in range(501):

    optimizer.zero_grad()
    output = model(marks1)

    Loss = loss_function(output,marks2)
    Loss.backward()

    if (epoch + 1) % 50 == 0:
        print(f'Epoch {epoch+1} : Loss {Loss.item()}')


    
    


Epoch 50 : Loss 0.773064374923706
Epoch 100 : Loss 0.773064374923706
Epoch 150 : Loss 0.773064374923706
Epoch 200 : Loss 0.773064374923706
Epoch 250 : Loss 0.773064374923706
Epoch 300 : Loss 0.773064374923706
Epoch 350 : Loss 0.773064374923706
Epoch 400 : Loss 0.773064374923706
Epoch 450 : Loss 0.773064374923706
Epoch 500 : Loss 0.773064374923706


In [29]:
a = torch.tensor([[1.0,2.3,4.5]])
b = torch.tensor([[1,2,3]])
result = a/b + 3
print(result)

tensor([[4.0000, 4.1500, 4.5000]])


In [30]:
print(a.dtype)

torch.float32


In [31]:
print(b.shape)

torch.Size([1, 3])


In [33]:
number = torch.tensor([[2.3] , [4.3] , [5.4]])
weight = 2
bias = 1

print(number*weight+bias)


tensor([[ 5.6000],
        [ 9.6000],
        [11.8000]])


In [35]:
number1 = torch.tensor([[1.0,2.0,3.0] , [4.0,5.0,6.0]])
number2 = torch.tensor([10,12,13])
number3 = number1*number2
print(number3)

tensor([[10., 24., 39.],
        [40., 60., 78.]])


In [42]:
print(number3[:,0])

tensor([10., 40.])


In [53]:
print(number3[1][1].item())

60.0


In [55]:
float_tensor = torch.tensor([[10,20,30]] , dtype = torch.float32)
int_tensor = torch.tensor([[45,50,60]] , dtype = torch.int64)
mixed_tensor = float_tensor + int_tensor
print(mixed_tensor.dtype)

torch.float32


In [68]:
e = torch.tensor([[40,50,60]])
print(e)
print(e.unsqueeze(dim=2))

tensor([[40, 50, 60]])
tensor([[[40],
         [50],
         [60]]])


In [7]:
tensor_a = torch.tensor([[1,2]])
tensor_b = torch.tensor([[3,4]])
concat_tensor = torch.cat((tensor_a,tensor_b) , dim=1)
print(concat_tensor)

tensor([[1, 2, 3, 4]])


In [11]:
ones = torch.ones(1,2)
print(zero)

tensor([[0., 0.]])


In [37]:
#Data Preparation
from torch.utils.data import DataLoader , TensorDataset
X = torch.tensor(df['distance_miles'].values , dtype = torch.float32)
y = torch.tensor(df['time_of_day_hours'].values , dtype = torch.float32)
dataset = TensorDataset(X,y)
load = DataLoader(dataset , batch_size = 32 , shuffle = True)
print(load)

In [41]:
 # ── 2. Prepare Features and Target ───────────────────────────
  # Features: distance, time_of_day, is_weekend
X = torch.tensor(df[['distance_miles', 'time_of_day_hours', 'is_weekend']].values,
                   dtype=torch.float32)   # shape → (100, 3)

  # Target: delivery_time_minutes
y = torch.tensor(df['delivery_time_minutes'].values,
                   dtype=torch.float32).unsqueeze(1)  # shape → (100, 1)

print("X shape:", X.shape)   # torch.Size([100, 3])
print("y shape:", y.shape)   # torch.Size([100, 1])

  # ── 3. Normalize Features ─────────────────────────────────────
X = (X - X.mean(dim=0)) / X.std(dim=0)

  # ── 4. Create DataLoader ──────────────────────────────────────
dataset = TensorDataset(X, y)
load    = DataLoader(dataset, batch_size=32, shuffle=True)

  # ── 5. Define Model ───────────────────────────────────────────
model = nn.Sequential(
      nn.Linear(3, 64),    # 3 input features
      nn.ReLU(),
      nn.Linear(64, 32),
      nn.ReLU(),
      nn.Linear(32, 1)     # 1 output: delivery time
)

  # ── 6. Loss and Optimizer ─────────────────────────────────────
loss_fn   = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

  # ── 7. Training Loop ──────────────────────────────────────────
for epoch in range(500):
    model.train()
    epoch_loss = 0

    for X_batch, y_batch in load:
        optimizer.zero_grad()
        predictions = model(X_batch)
        loss        = loss_fn(predictions, y_batch)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()

    if (epoch + 1) % 50 == 0:
          avg_loss = epoch_loss / len(load)
          print(f"Epoch [{epoch+1}/500]  Loss: {avg_loss:.4f}")

  # ── 8. Test Prediction ────────────────────────────────────────
model.eval()
with torch.no_grad():
      sample = torch.tensor([[5.5, 8.5, 0]], dtype=torch.float32)
      sample = (sample - X.mean(dim=0)) / X.std(dim=0)  # normalize
      pred   = model(sample)
      print(f"\nPredicted delivery time: {pred.item():.2f} minutes")

  


X shape: torch.Size([100, 3])
y shape: torch.Size([100, 1])
Epoch [50/500]  Loss: 115.7154
Epoch [100/500]  Loss: 43.5580
Epoch [150/500]  Loss: 38.4646
Epoch [200/500]  Loss: 35.1401
Epoch [250/500]  Loss: 33.0169
Epoch [300/500]  Loss: 42.0145
Epoch [350/500]  Loss: 32.0101
Epoch [400/500]  Loss: 31.7410
Epoch [450/500]  Loss: 49.7395
Epoch [500/500]  Loss: 29.1056

Predicted delivery time: 139.36 minutes
