In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [26]:
data = pd.read_csv(r'C:\Users\SriniAchuthan\OneDrive\Documents\Machine-Learning-A-Z-Codes-Datasets\Machine Learning A-Z\Part 1 - Data Preprocessing\Section 2 -------------------- Part 1 - Data Preprocessing --------------------\Python\Data.csv')
print(data)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [27]:
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 42)
print(X_train)

[['France' 35.0 58000.0]
 ['France' 44.0 72000.0]
 ['France' 48.0 79000.0]
 ['Germany' 30.0 54000.0]
 ['France' 37.0 67000.0]
 ['Germany' 40.0 nan]
 ['Spain' 38.0 61000.0]
 ['Spain' nan 52000.0]]


In [28]:
print(X_test)

[['Germany' 50.0 83000.0]
 ['Spain' 27.0 48000.0]]


In [29]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')
imputer.fit(X[:,1:3])
X[: , 1:3] =  imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [30]:

# df = pd.DataFrame({
#       'Age':    [25, np.nan, 30, 35],
#       'Salary': [50000, 60000, np.nan, 70000]
#   })

#   # Fill missing with mean
# imputer = SimpleImputer(strategy='mean')
# df_filled = imputer.fit_transform(df)

# print(df_filled)

In [31]:
df = pd.DataFrame({
    'Age' : [24 , np.nan , 34, 45],
    'Salary' : [50000 , 60000 , np.nan , 70000]
})

imputer = SimpleImputer(strategy = 'median')
df_filled = imputer.fit_transform(df)
print(df_filled)

[[2.4e+01 5.0e+04]
 [3.4e+01 6.0e+04]
 [3.4e+01 6.0e+04]
 [4.5e+01 7.0e+04]]


In [32]:
diabetes = pd.read_csv(r'C:\Users\SriniAchuthan\diabetes.csv')
print(diabetes)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [33]:
X = diabetes.iloc[:,:-1].values
y = diabetes.iloc[:,-1].values

imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')
X_filled = imputer.fit_transform(X)
print(X_filled)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [34]:
q = pd.DataFrame(X_filled)
print(q)

        0      1     2     3      4     5      6     7
0     6.0  148.0  72.0  35.0    0.0  33.6  0.627  50.0
1     1.0   85.0  66.0  29.0    0.0  26.6  0.351  31.0
2     8.0  183.0  64.0   0.0    0.0  23.3  0.672  32.0
3     1.0   89.0  66.0  23.0   94.0  28.1  0.167  21.0
4     0.0  137.0  40.0  35.0  168.0  43.1  2.288  33.0
..    ...    ...   ...   ...    ...   ...    ...   ...
763  10.0  101.0  76.0  48.0  180.0  32.9  0.171  63.0
764   2.0  122.0  70.0  27.0    0.0  36.8  0.340  27.0
765   5.0  121.0  72.0  23.0  112.0  26.2  0.245  30.0
766   1.0  126.0  60.0   0.0    0.0  30.1  0.349  47.0
767   1.0   93.0  70.0  31.0    0.0  30.4  0.315  23.0

[768 rows x 8 columns]


In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder' , OneHotEncoder(), [0])] , remainder = 'passthrough')
ct.fit_transform(X)

array([[ 0.   ,  0.   ,  0.   , ..., 33.6  ,  0.627, 50.   ],
       [ 0.   ,  1.   ,  0.   , ..., 26.6  ,  0.351, 31.   ],
       [ 0.   ,  0.   ,  0.   , ..., 23.3  ,  0.672, 32.   ],
       ...,
       [ 0.   ,  0.   ,  0.   , ..., 26.2  ,  0.245, 30.   ],
       [ 0.   ,  1.   ,  0.   , ..., 30.1  ,  0.349, 47.   ],
       [ 0.   ,  1.   ,  0.   , ..., 30.4  ,  0.315, 23.   ]],
      shape=(768, 24))

In [36]:
dcolor = pd.DataFrame({
    'Color' : ['Red' , 'Green' , 'Blue']
})

color = ct.fit_transform(dcolor)
print(color)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [37]:
data2 = pd.read_csv(r'C:\Users\SriniAchuthan\Downloads\titanic.csv')
print(data2)

     PassengerId  Survived  Pclass  \
0              2         1       1   
1              4         1       1   
2              7         0       1   
3             11         1       3   
4             12         1       1   
..           ...       ...     ...   
178          872         1       1   
179          873         0       1   
180          880         1       1   
181          888         1       1   
182          890         1       1   

                                                  Name     Sex   Age  SibSp  \
0    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
1         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
2                              McCarthy, Mr. Timothy J    male  54.0      0   
3                      Sandstrom, Miss. Marguerite Rut  female   4.0      1   
4                             Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ... 

In [54]:
print(data2.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [57]:
  # Only encode actual categorical columns
categorical_features = ['Sex']  # Age is numeric, Name has high cardinality

ct = ColumnTransformer(
      transformers=[('encoder', OneHotEncoder(handle_unknown='ignore'), categorical_features)],
      remainder='passthrough'
  )

data2_filled = ct.fit_transform(data2)
dat2 = np.array(data2_filled)
print(dat2)

[[1.0 0.0 2 ... 71.2833 'C85' 'C']
 [1.0 0.0 4 ... 53.1 'C123' 'S']
 [0.0 1.0 7 ... 51.8625 'E46' 'S']
 ...
 [1.0 0.0 880 ... 83.1583 'C50' 'C']
 [1.0 0.0 888 ... 30.0 'B42' 'S']
 [0.0 1.0 890 ... 30.0 'C148' 'C']]


In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size = 0.2 , random_state = 42)
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

print("\n----Scaled X-train----")
print(X_train_scaled)


print("\n----Scaled X_test----")
print(X_test_scaled)



----Scaled X-train----
[[-0.52639686 -1.15139792 -3.75268255 ... -4.13525578 -0.49073479
  -1.03594038]
 [ 1.58804586 -0.27664283  0.68034485 ... -0.48916881  2.41502991
   1.48710085]
 [-0.82846011  0.56687102 -1.2658623  ... -0.42452187  0.54916055
  -0.94893896]
 ...
 [ 1.8901091  -0.62029661  0.89659009 ...  1.76054443  1.981245
   0.44308379]
 [-1.13052335  0.62935353 -3.75268255 ...  1.34680407 -0.78487662
  -0.33992901]
 [-1.13052335  0.12949347  1.43720319 ... -1.22614383 -0.61552223
  -1.03594038]]

----Scaled X_test----
[[ 0.68185612 -0.71402038 -0.61712658 ...  0.26073561 -0.11637247
   0.87809089]
 [-0.52639686 -0.27664283  0.30191569 ...  0.48053518 -0.954231
  -1.03594038]
 [-0.52639686 -0.40160784 -0.29275872 ... -0.15300476 -0.9245197
  -1.03594038]
 ...
 [ 1.28598261 -0.80774414  0.13973176 ...  0.62275843  0.04703966
   2.0961108 ]
 [-0.52639686  0.78555979  0.03160914 ... -0.51502758 -0.39268751
  -0.33992901]
 [ 1.28598261 -1.46381046  0.03160914 ...  0.42881763  0

In [68]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

data3 = pd.read_csv(r'C:\Users\SriniAchuthan\Downloads\winequality-red.csv', delimiter=';')

print(data3.columns.tolist())  # verify column names

X = data3.drop('quality', axis=1).values
y = data3['quality'].values.reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler_x = StandardScaler()
scaler_y = StandardScaler()

X_scaled_train = scaler_x.fit_transform(X_train)
y_scaled_train = scaler_y.fit_transform(y_train)

X_scaled_test = scaler_x.transform(X_test)
y_scaled_test = scaler_y.transform(y_test)

print('\n----Scaled X_train----')
print(X_scaled_train)

print('\n----Scaled y_train----')
print(y_scaled_train)

print('\n----Scaled X_test----')
print(X_scaled_test)

print('\n----Scaled y_test----')
print(y_scaled_test)

['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality']

----Scaled X_train----
[[-0.4775328   0.37564973 -0.63914994 -0.37026339  0.0168002  -0.56254395
  -0.45018379  0.59648091  1.1097633  -0.1987616  -0.83941785]
 [-0.4775328   0.65520302 -0.63914994 -0.30137718  0.15120179 -1.46261427
  -0.70743166  0.59648091  1.1097633  -0.1987616  -0.83941785]
 [-0.55881498  0.30576141 -0.63914994 -0.78358067 -1.32721571  0.33752637
  -1.26480207 -2.34004049  0.13235709 -1.09318879  0.77226442]
 [-0.15240409  1.07453296 -0.43863231 -0.02583233  2.30162725  0.33752637
   0.15006126 -0.13764944 -0.92649964  0.69566559  0.235037  ]
 [-0.39625062 -0.74256343  1.16550871  2.59184375 -0.52080617  1.23759669
   2.20804428  0.59648091 -0.19344498  2.18637758  2.11533298]
 [-0.4775328   0.65520302 -0.63914994 -0.30137718  0.15120179 -1.46261427
  -0.70743166  0.59648091  1.10976

In [65]:
print(data3.dtypes)

fixed acidity;"volatile acidity";"citric acid";"residual sugar";"chlorides";"free sulfur dioxide";"total sulfur dioxide";"density";"pH";"sulphates";"alcohol";"quality"    object
dtype: object
